version: '3.8'
services:
    server:
        build: api
        expose:
            - 8080
        networks:
            - my_net
        restart: always
    client:
        build: test_suit_for_api
        networks:
            - my_net

networks:
    my_net:
        driver: bridge


